# Generated by Django 2.1.3 on 2018-11-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='status',
        ),
        migrations.AddField(
            model_name='container',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
