# Generated by Django 2.1.3 on 2018-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181128_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='cid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
