# Generated by Django 2.1.3 on 2018-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
