# Generated by Django 2.1.3 on 2018-11-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181128_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country'),
        ),
    ]
